on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco Pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco Logon
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: apikey --key ${{ secrets.CHOCOLATEY_TOKEN }} --source https://push.chocolatey.org/
      -
        name: Get Aspidites Version
        run: echo "VERSION = ${GITHUB_REF##*/}" >> GITHUB_ENV
      -
        name: Choco Push
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push MyPackage.${{ env.VERSION }}.nupkg --source https://push.chocolatey.org/


