name: 🐍 📦 PyPI

on:
  push:
    tags:
      - v*

jobs:
  manylinux-deploy:
      name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
           python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Create manylinux wheel
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: 'cp37-cp37m'
          build-requirements: 'cython pyparsing mypy pyrsistent pytest future'
          package-path: '.'

      - name: Publish wheels to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload -r testpypi dist/*-manylinux*.whl


      - name: Publish wheels to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*-manylinux*.whl

      - name: Send a Tweet
        continue-on-error: true
        uses: ethomson/send-tweet-action@v1
        with:
            status: "📦 New PyPI package: Aspidites ${{ github.event.head_commit.message }}! 🎉🎉🎉
            Check it out: https://pypi.org/project/Aspidites"
            consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
            consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
            access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
