# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9 in pipenv
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv wheel cython
        pipenv lock
        pipenv sync -d
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=Aspidites --cov-report=xml
    - name: Upload Coverage to codecov.io
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
    - name: Upload Coverage to codeclimate.com
      uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 5bcc9d60bb439f75e102507e595434a393e9be017010223f6f3bc61cce2f5802
      with:
        coverageCommand: coverage ./coverage.xml

