# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.9.6
          - 3.8.11

    steps:
      - uses: actions/checkout@v2
      - name: Test Python Versions
        uses: gabrielfalcao/pyenv-action@v5
        with:
         default: "${{ matrix.python }}"
         command: |
                pip install -U pip pipenv wheel cython
                pipenv lock
                pipenv sync -d
                pipenv run pytest --cov=Aspidites --cov-report=xml
                rm -rf Pipfile.lock

      - name: Upload Coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 5bcc9d60bb439f75e102507e595434a393e9be017010223f6f3bc61cce2f5802

